### ISSUE TITLE
please add wayland support

### ISSUE THREAD

**Issue by faridcher** [ropery/FFcast#27]
```
~$ echo $XDG_SESSION_TYPE 
wayland
~$ ffcast -w pad '20 2 2' png screenshot-%s.png
:: please click once in target window
```

nothing happens when I click on a window.

**Comment by ropery** [comment]
Good day. I'm afraid for Wayland you'd have to look for another tool.

The reason is that Wayland is a whole 'nother beast than X11. FFcast delegates the actual work to tools that only work under X11. To support Wayland would require finding/making equivalent tools, *if* such tools are possible under Wayland.
